version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.8.4"
    steps:
      - checkout
      - run: python3 Main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.8.4"
    steps:
      - checkout
      - run: python3 Main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build